blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog_index, name="blog_index"),
    path('<int:pk>/', views.blog_detail, name="blog_detail"),
    path('<category>/', views.blog_category, name="blog_category"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),
    path('dashboard/', include('users.urls')),
    path('oauth/', include('social_django.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

projects/urls.py
from django.urls import path
from projects import views


app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>/', views.project_detail, name="project_detail"),
]

users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('', views.dashboard, name="dashboard"),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

core/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name",
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!",
        }
    ))

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
from blog.forms import CommentForm

def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts
    }

    return render(request, "blog_index.html", context)


def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(
        '-created_on'
    )
    context = {
        "category": category,
        "posts": posts
    }

    return render(request, "blog_category.html", context)


def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post,
            )
            comment.save()

    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog_detail.html", context)

core/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
from django.shortcuts import render
from projects.models import Project


def all_projects(request):
    # query db to get all rpject objects
    projects = Project.objects.all()
    return render(request, 'projects/all_projects.html', {'projects': projects})

def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'projects/detail.html', {'project': project})

users/views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'users/dashboard.html')

def register(request):
    if request.method == "GET":
        return render(
            request, "users/register.html", {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.backend = "django.contrib.auth.backends.ModelBackend"
            user.save()
            login(request, user)
            return redirect(reverse("dashboard"))

blog/templates/blog_category.html
{% extends "projects/base.html" %}

{% block content %}

    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <h1 class="py-5">{{ category | title }}</h1>
        {% for post in posts %}
        <div class="post-preview">
          <a class="text-decoration-none" href="{% url 'blog_detail' post.pk %}">
            <h2 class="post-title text-success">
                {{ post.title }}
            </h2>
          </a>
          <p class="post-meta">Posted on
            {{ post.created_on.date }} under
                {% for category in post.categories.all %}
                <a class="text-decoration-none" href="{% url 'blog_category' category.name %}">
                    {{ category.name }}
                </a>&nbsp;
                {% endfor %}
          </p>

        </div>

        {% endfor %}
      </div>
    </div>
{% endblock content %}

blog/templates/blog_detail.html
{% extends 'projects/base.html' %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead bg-success bg-gradient">
    <div class="overlay"></div>
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{ post.title }}</h1>
            <span class="meta">Posted on
            {{ post.created_on.date }} under
                {% for category in post.categories.all %}
                <a class="text-decoration-none text-white" href="{% url 'blog_category' category.name %}">
                    {{ category.name }}
                </a>&nbsp;
                {% endfor %}
            </span>
          </div>
        </div>
      </div>
  </header>

  <!-- Post Content -->
  <article>
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>{{ post.body | linebreaks }}</p>



      <br>
      <h3>Leave a comment:</h3>
      <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group py-2">
          {{ form.author }}
        </div>
        <div class="form-group py-2">
          {{ form.body }}
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
      <br>

      <h3>Comments:</h3>
      {% for comment in comments %}
      <p>
        On {{ comment.created_on.date }}
        <b>{{ comment.author }}</b> wrote:
      </p>
      <p>{{ comment.body }}</p>
      <hr>
      {% endfor %}
          </div>
      </div>
  </article>
{% endblock content %}

blog/templates/blog_index.html
{% extends "projects/base.html" %}

{% block content %}

    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <h1 class="py-5">Blogs</h1>
        {% for post in posts %}
        <div class="post-preview">
          <a class="text-decoration-none" href="{% url 'blog_detail' post.pk %}">
            <h2 class="post-title text-success">
                {{ post.title }}
            </h2>
          </a>
          <p class="post-meta">Posted on
            {{ post.created_on.date }} under
                {% for category in post.categories.all %}
                <a class="text-decoration-none" href="{% url 'blog_category' category.name %}">
                    {{ category.name }}
                </a>&nbsp;
                {% endfor %}
          </p>

        </div>

        {% endfor %}
      </div>
    </div>
{% endblock content %}

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}
    <main class="container py-5">
      <h1>Projects</h1>
        <hr class="my-5">
        <div class="row" data-masonry='{"percentPosition": true }'>
            <div class="col-sm-6 col-lg-4 mb-4">
              <div class="card bg-primary bg-gradient p-3 shadow-sm">
                <figure class="p-3 mb-0">
                  <blockquote class="blockquote">
                    <p class="fw-bolder">Whatever it takes.</p>
                  </blockquote>
                  <figcaption class="blockquote-footer mb-0 mt-1 text-light">
                    Steve Rogers in <cite title="Source Title">Infinity Saga</cite>
                  </figcaption>
                </figure>
              </div>
            </div>
                {% for project in projects %}
                    <div class="col-sm-6 col-lg-4 mb-4">
                      <div class="card shadow-sm">
                        <img src="{% static project.image %}" class="card-img-top" alt="{{ project.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{project.title}}</h5>
                            <p class="card-text">{{project.description}}</p>
                            <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-primary">Read More</a>
                        </div>
                      </div>
                    </div>
                {% endfor %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="django portfolio app">
    <meta name="author" content="AbyKal">
    <title>DJ Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
    <header>
      <div class="collapse bg-dark bg-gradient" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">DJ Portfolio. A portfolio app made in Django and Python, showing off projects and blogs. And more coming soon.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="{% url 'projects:all_projects'  %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>DJ Portfolio</strong>
          </a>
          <a class="nav-link text-white text-decoration-none" href="{% url 'projects:all_projects' %}">Projects</a>
          <a class="nav-link text-white text-decoration-none" href="{% url 'blog_index' %}">Blog</a>

          <button class="navbar-toggler bg-success" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        </div>
      </div>
    </header>


    <div class="container pt-5">
        {% block content %}

        {% endblock content %}
    </div>


    <!-- Bootstrap Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <!-- Masonry -->
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
</body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}
    <main class="container py-5">
      <h1>Project Details</h1>
        <hr class="my-5">
        <div class="row">
            <div class="col-md-8">
                <img src="{% static project.image %}" alt="project image"/>
            </div>
        </div>
        <div class="col-md-4">
            <h2 class="mt-3">{{project.title}}</h2>
            <p class="text-secondary">{{project.description}}</p>
            <p>Built with: <span class="badge bg-success">{{project.technology}}</span></p>
        </div>
       </main>
{% endblock content %}

users/templates/users/dashboard.html
{% extends 'projects/base.html' %}

{% block content %}

<div class="p-3 mb-2 bg-warning text-dark">
    <h1>Hello, {{ user.username|default:'Guest' }}!</h1>
</div>

<div>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="btn btn-primary stretched-link">Logout</a>
        <a href="{% url 'password_change' %}" class="btn btn-danger stretched-link">Change password</a>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-success stretched-link">Login</a>
    {% endif %}
</div>

{% endblock content  %}